In [1]:
import tensorflow.keras
import numpy as np
import cv2

# 모델 위치
model_filename ='C:\\Users\\Administrator\\keras_model.h5'

# 케라스 모델 가져오기
model = tensorflow.keras.models.load_model(model_filename)

# 카메라를 제어할 수 있는 객체
capture = cv2.VideoCapture(0)

# 카메라 길이 너비 조절
capture.set(cv2.CAP_PROP_FRAME_WIDTH, 320)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 240)

# 이미지 처리하기
def preprocessing(frame):
    #frame_fliped = cv2.flip(frame, 1)
    # 사이즈 조정 티쳐블 머신에서 사용한 이미지 사이즈로 변경해준다.
    size = (224, 224)
    frame_resized = cv2.resize(frame, size, interpolation=cv2.INTER_AREA)
    
    # 이미지 정규화
    # astype : 속성
    frame_normalized = (frame_resized.astype(np.float32) / 127.0) - 1

    # 이미지 차원 재조정 - 예측을 위해 reshape 해줍니다.
    # keras 모델에 공급할 올바른 모양의 배열 생성
    frame_reshaped = frame_normalized.reshape((1, 224, 224, 3))
    #print(frame_reshaped)
    return frame_reshaped

# 예측용 함수
def predict(frame):
    prediction = model.predict(frame)
    return prediction

while True:
    ret, frame = capture.read()

    if cv2.waitKey(100) > 0: 
        break

    preprocessed = preprocessing(frame)
    prediction = predict(preprocessed)
    maxind = np.argmax(prediction)
    print(maxind)

#     if (prediction[0,0] < prediction[0,1]):
    if maxind == 2:
        print('brush')
        print(prediction)
        cv2.putText(frame, 'brush', (0, 25), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0))
        
        cap = cv2.VideoCapture('C:\\Users\\Administrator\\brush.mp4') # mp4 파일
        
        while True:
            ret, img = cap.read()
            cv2.imshow('result', img)
            if cv2.waitKey(40) == ord('q'):
                break
        cap.release() # 동영상 파일 닫고 메모리 해제
        
    elif maxind == 1:
        cv2.putText(frame, 'X', (0, 25), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0))
        print('X')
        
    elif maxind == 0:
        cv2.putText(frame, 'hand on', (0, 25), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0))
        print('hand on')
        
        cap = cv2.VideoCapture('C:\\Users\\Administrator\\hand.mp4')
        
        while True:
            ret, img = cap.read()
            cv2.imshow('result', img)
            if cv2.waitKey(20) == ord('q'):
                break
        cap.release()
    
    

    cv2.imshow("VideoFrame", frame)

1/1 [==============================] - 1s 585ms/step
0
hand on
1/1 [==============================] - 0s 160ms/step
0
hand on
1/1 [==============================] - 0s 24ms/step
0
hand on
1/1 [==============================] - 0s 24ms/step
2
brush
[[9.6528686e-04 2.9091738e-04 9.9874383e-01]]
1/1 [==============================] - 0s 24ms/step
2
brush
[[2.7018550e-04 1.0993941e-04 9.9961984e-01]]
1/1 [==============================] - 0s 24ms/step
2
brush
[[0.1690793  0.02440089 0.80651975]]
1/1 [==============================] - 0s 24ms/step
0
hand on


error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
